package FlightPackage;

import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * ----Flight Booking System--------- Developed by - Harsh Joshi 
 *                                                   Bhavya Giri Goswami
 */
/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 *
 */
public class BookingHistory extends javax.swing.JFrame {

    /**
     * Creates new form BookingHistory
     */
    public BookingHistory() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("AWT-Plane.png"));
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistTBL = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Cancelbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ShowTbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Booking History");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(927, 514));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(927, 514));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setOpaque(false);

        HistTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PNR", "User ID", "User name", "Flight no", "From", "To", "Flight Date", "Booking Date", "Booking Time", "Class", "Tickets", "Rate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HistTBL.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        HistTBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HistTBL.setOpaque(false);
        HistTBL.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(HistTBL);

        jScrollPane1.setBounds(20, 80, 880, 270);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(14, 32, 93));
        jLabel2.setText(" Booking History");
        jLabel2.setBounds(20, 30, 370, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.MODAL_LAYER);

        Cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Cancelbtn.setText("Cancel Ticket");
        Cancelbtn.setPreferredSize(new java.awt.Dimension(105, 25));
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });
        Cancelbtn.setBounds(705, 370, 120, 25);
        jLayeredPane1.add(Cancelbtn, javax.swing.JLayeredPane.DRAG_LAYER);

        Backbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Backbtn.setText(" Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        Backbtn.setBounds(740, 470, 80, 30);
        jLayeredPane1.add(Backbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/abstract-blue-gradient-colors.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setPreferredSize(new java.awt.Dimension(928, 514));
        jLabel1.setBounds(0, 0, 928, 514);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ShowTbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ShowTbtn.setText("Show Ticket");
        ShowTbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTbtnActionPerformed(evt);
            }
        });
        ShowTbtn.setBounds(85, 370, 120, 25);
        jLayeredPane1.add(ShowTbtn, javax.swing.JLayeredPane.PALETTE_LAYER);
        jSeparator1.setBounds(0, 70, 928, 2);
        jLayeredPane1.add(jSeparator1, javax.swing.JLayeredPane.PALETTE_LAYER);
        jSeparator2.setBounds(0, 20, 928, 2);
        jLayeredPane1.add(jSeparator2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/iconlogo.png"))); // NOI18N
        jLabel3.setBounds(140, 0, 200, 80);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Statement connect() throws ClassNotFoundException, SQLException {//Connection Method

        Class.forName("com.mysql.jdbc.Driver");
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight_book", "root", "ipqwe320");
        Statement stmt = con.createStatement();
        return stmt;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.requestFocus();
        DefaultTableModel tmodel = (DefaultTableModel) HistTBL.getModel();
        try {
            String CmdSql = "select booking.*,flights.from_f,flights.to_f from booking,flights where user_name ='" + UserGlobal.userName + "' and booking.flightno = flights.flightno order by pnr_no;";
            
            ResultSet rs = connect().executeQuery(CmdSql);
            while (rs.next()) {
                int PNR = rs.getInt("pnr_no");
                int uID = rs.getInt("idno");
                String Uname = rs.getString("user_name");
                int Fno = rs.getInt("flightno");
                String Dflight = rs.getString("date_flight");
                String Dbook = rs.getString("date_book");
                String Tbook = rs.getString("time_book");
                String Fclass = rs.getString("class");
                int tickets = rs.getInt("tickets");
                int rate = rs.getInt("rate");
                String From = rs.getString("from_f");
                String To = rs.getString("to_f");
                String canceled = rs.getString("canceled");
                String cancelDisp = "";
                if (canceled.equals("")) {
                    cancelDisp = "";
                } else if (canceled.equals("Y")) {
                    cancelDisp = "Canceled";
                }
                tmodel.addRow(new Object[]{PNR, uID, Uname, Fno, From, To, Dflight, Dbook, Tbook, Fclass, tickets, rate, cancelDisp});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        // TODO add your handling code here:
        if(HistTBL.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(this,"No transaction is selected!\nPlease select a transaction.","Warning!",JOptionPane.WARNING_MESSAGE);
        }else{
        String Status = HistTBL.getModel().getValueAt(HistTBL.getSelectedRow(),12).toString();
        if(Status.equals("")){
        int DResult = JOptionPane.showConfirmDialog(this,"Do you want to cancel the booking?","Booking Cancelation",JOptionPane.YES_NO_OPTION);
        if(DResult == 0){
        
        DefaultTableModel Histmodel = (DefaultTableModel) HistTBL.getModel();
        int getPNR = Integer.parseInt(HistTBL.getValueAt(HistTBL.getSelectedRow(), 0).toString());


        try {
            
            String CmdSql = "update booking set canceled = 'Y' where pnr_no = " + getPNR + ";";
            
            int rs = connect().executeUpdate(CmdSql);
           
            if (rs == 0) {
                JOptionPane.showMessageDialog(this, "An error occured. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }else 
            { Histmodel.setValueAt("Canceled", HistTBL.getSelectedRow(), 12);}

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }else {
          
        }
        }
        else{
          JOptionPane.showMessageDialog(this,"This booking has already been canceled.","",JOptionPane.INFORMATION_MESSAGE);  
        }
        }
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainForm().setVisible(true);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void ShowTbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTbtnActionPerformed
        // TODO add your handling code here:
        if(HistTBL.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(this,"No transaction is selected!\nPlease select a transaction.","Warning!",JOptionPane.WARNING_MESSAGE);
        }else{
        BookingVar.PNR = Integer.parseInt(HistTBL.getValueAt(HistTBL.getSelectedRow(), 0).toString());
        new Ticket().setVisible(true);
        }
    }//GEN-LAST:event_ShowTbtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new MainForm().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BookingHistory().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JTable HistTBL;
    private javax.swing.JButton ShowTbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
