package FlightPackage;

import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * ----Flight Booking System--------- Developed by - Harsh Joshi Bhavya Giri
 * Goswami
 */
/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 *
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("AWT-Plane.png"));
        setIconImage(icon.getImage());

    }


    public static boolean isDateValid(String date) {
        // isDateValid Method created - Checks validity of the input date
        try {
            DateFormat Df = new SimpleDateFormat("dd/MM/yyyy");
            Df.setLenient(false);
            Df.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AvlFlights = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ClassCmb = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        No_seats = new javax.swing.JTextField();
        AirLbl = new javax.swing.JLabel();
        FromLbl = new javax.swing.JLabel();
        ToLbl = new javax.swing.JLabel();
        BookBTN = new javax.swing.JButton();
        DLbl = new javax.swing.JLabel();
        ALbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TtlCtxt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ecoRateLbl = new javax.swing.JLabel();
        busRateLbl = new javax.swing.JLabel();
        firstRateLbl = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        SeatLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        datetxt = new javax.swing.JFormattedTextField();
        FindBTN = new javax.swing.JButton();
        CancelBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Domestic Flights");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(246, 209, 138));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/soft_light_wave_abstract_background-wide.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 800, 530);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 22)); // NOI18N
        jLabel2.setText("Book Domestic Flights");
        jLabel2.setBounds(20, 10, 420, 40);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

        AvlFlights.setModel(new DefaultComboBoxModel());
        AvlFlights.setToolTipText("Select a filght");
        AvlFlights.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AvlFlights.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AvlFlightsItemStateChanged(evt);
            }
        });
        AvlFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvlFlightsActionPerformed(evt);
            }
        });
        AvlFlights.setBounds(160, 90, 210, 22);
        jLayeredPane1.add(AvlFlights, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel3.setLabelFor(AvlFlights);
        jLabel3.setText("Available Flights");
        jLabel3.setBounds(40, 90, 120, 20);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.PALETTE_LAYER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setLabelFor(AirLbl);
        jLabel4.setText("Airline");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setLabelFor(FromLbl);
        jLabel5.setText("From");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setLabelFor(ToLbl);
        jLabel6.setText("To");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setLabelFor(DLbl);
        jLabel7.setText("Departure Time");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setLabelFor(ALbl);
        jLabel8.setText("Arrival Time");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setLabelFor(ClassCmb);
        jLabel9.setText("Class");

        ClassCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select a Class-", "Economy", "Bussiness", "First Class" }));
        ClassCmb.setToolTipText("Select a class");
        ClassCmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClassCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassCmbActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setLabelFor(No_seats);
        jLabel10.setText("Number of Seats");

        No_seats.setText("0");
        No_seats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                No_seatsKeyReleased(evt);
            }
        });

        AirLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AirLbl.setToolTipText("Airline");
        AirLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        FromLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ToLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BookBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BookBTN.setText("Book");
        BookBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookBTNActionPerformed(evt);
            }
        });

        DLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ALbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setLabelFor(TtlCtxt);
        jLabel15.setText("Total Cost -");

        TtlCtxt.setToolTipText("Total cost");
        TtlCtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setToolTipText("Rates");
        jPanel2.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setLabelFor(firstRateLbl);
        jLabel13.setText("Economy");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setLabelFor(firstRateLbl);
        jLabel12.setText("Rate");

        ecoRateLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        busRateLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        firstRateLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setLabelFor(firstRateLbl);
        jLabel17.setText("First Class");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setLabelFor(firstRateLbl);
        jLabel16.setText("Bussiness");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel12)
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(firstRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ecoRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(busRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(120, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 132, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ecoRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(busRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(firstRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setLabelFor(firstRateLbl);
        jLabel18.setText("Seats Available");

        SeatLbl.setToolTipText("Available seats");
        SeatLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BookBTN)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(AirLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(23, 23, 23)
                                                .addComponent(FromLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(DLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(ALbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(ToLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(105, 105, 105)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(ClassCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(No_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TtlCtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SeatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AirLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FromLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ALbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TtlCtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClassCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(No_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(BookBTN)
                .addContainerGap())
        );

        jPanel1.setBounds(30, 140, 740, 360);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setLabelFor(datetxt);
        jLabel11.setText("Travel Date");
        jLabel11.setBounds(70, 60, 80, 25);
        jLayeredPane1.add(jLabel11, javax.swing.JLayeredPane.PALETTE_LAYER);

        datetxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        datetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datetxt.setToolTipText("DD/MM/YYYY");
        datetxt.setBounds(160, 60, 123, 25);
        jLayeredPane1.add(datetxt, javax.swing.JLayeredPane.PALETTE_LAYER);

        FindBTN.setText("Find Flights");
        FindBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FindBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindBTNActionPerformed(evt);
            }
        });
        FindBTN.setBounds(380, 60, 100, 25);
        jLayeredPane1.add(FindBTN, javax.swing.JLayeredPane.PALETTE_LAYER);

        CancelBTN.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CancelBTN.setForeground(new java.awt.Color(255, 2, 2));
        CancelBTN.setText("X");
        CancelBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });
        CancelBTN.setBounds(740, 10, 50, 40);
        jLayeredPane1.add(CancelBTN, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Statement connect() throws ClassNotFoundException, SQLException {//Connection Method

        Class.forName("com.mysql.jdbc.Driver");
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight_book", "root", "ipqwe320");
        Statement stmt = con.createStatement();
        return stmt;
    }
    private void BookBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookBTNActionPerformed
        // TODO add your handling code here:
// Checks the validity of the date        
        if (!isDateValid(datetxt.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Date", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
       
// Creating new date format        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        try {
            Date date1 = sdf.parse(datetxt.getText()); // Gets input date
            Date cdate = new Date(); // Gives System date
// Comparing input date to system date           
            if (date1.compareTo(cdate) <= 0) {
                JOptionPane.showMessageDialog(this, "Booking not allowed before current date", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Booking not allowed before current date", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
// Comparing input no of seats with available seats.         
        BookingVar.NuSeats = Integer.parseInt(No_seats.getText());
        if (BookingVar.NuSeats > BookingVar.SeatsAvl) {
            JOptionPane.showMessageDialog(this, "Number of seats can't be more than available seats", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (BookingVar.NuSeats == 0) {
            JOptionPane.showMessageDialog(this, "Please enter the number of seats to be booked", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
// Connection and update command        
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight_book", "root", "ipqwe320");
            Statement stmt = con.createStatement();
            String CmdSql = "insert into booking (idno,user_name,flightno,date_flight,date_book,time_book,class,tickets,rate) values(" + UserGlobal.userID + ",'" + UserGlobal.userName + "'," + BookingVar.flightno + ",str_to_date('" + datetxt.getText() + "', '%d/%m/%Y'),now(),now(),'" + ClassCmb.getSelectedItem().toString() + "'," + BookingVar.NuSeats + "," + BookingVar.Rate + ")";
// Checks whether update command has been successfully executed or not. 

            int rowAff = stmt.executeUpdate(CmdSql, Statement.RETURN_GENERATED_KEYS);
            if (rowAff == 0) {
                JOptionPane.showMessageDialog(this, "An error occured while booking please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {

                ResultSet keys = stmt.getGeneratedKeys();
                keys.next();
                JOptionPane.showMessageDialog(this, "Ticket Booked! PNR No.:" + keys.getInt(1), "Success", JOptionPane.INFORMATION_MESSAGE);

                new MainForm().setVisible(true);
                this.dispose();
            }




        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BookBTNActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.requestFocus();
        datetxt.requestFocusInWindow();

    }//GEN-LAST:event_formWindowOpened

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        // TODO add your handling code here:
        new MainForm().setVisible(true);
        this.dispose(); // Disposes the window

    }//GEN-LAST:event_CancelBTNActionPerformed

    private void AvlFlightsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AvlFlightsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_AvlFlightsItemStateChanged

    private void AvlFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvlFlightsActionPerformed
        // TODO add your handling code here:
        try {
            String Sel = AvlFlights.getSelectedItem().toString();
            String CmdSql = "select * from flights where flightno + ',' + from_f + '-' + to_f ='" + Sel + "'";
            ResultSet rs = connect().executeQuery(CmdSql);
            rs.next();
            BookingVar.flightno = rs.getInt("flightno");
            BookingVar.flightId = rs.getString("flight_id");
            BookingVar.Airline = rs.getString("airline");
            BookingVar.from = rs.getString("from_f");
            BookingVar.to = rs.getString("to_f");
            BookingVar.ArrT = rs.getTime("arr_time").toString();
            BookingVar.DepT = rs.getTime("dep_time").toString();
            BookingVar.ecoSeats = rs.getInt("eco_seats");
            BookingVar.bussSeats = rs.getInt("buss_seats");
            BookingVar.firstSeats = rs.getInt("first_seats");
            BookingVar.firstRate = rs.getInt("rate_first");
            BookingVar.bussRate = rs.getInt("rate_buss");
            BookingVar.ecoRate = rs.getInt("rate_eco");

            ecoRateLbl.setText(BookingVar.ecoRate + "");
            busRateLbl.setText(BookingVar.bussRate + "");
            firstRateLbl.setText(BookingVar.firstRate + "");
            ecoRateLbl.setText(BookingVar.ecoRate + "");
            ecoRateLbl.setText(BookingVar.ecoRate + "");
            ecoRateLbl.setText(BookingVar.ecoRate + "");
            AirLbl.setText(BookingVar.Airline);
            FromLbl.setText(BookingVar.from);
            ToLbl.setText(BookingVar.to);
            DLbl.setText(BookingVar.DepT);
            ALbl.setText(BookingVar.ArrT);
            
            ClassCmb.setSelectedIndex(0);
            No_seats.setText("0");
            SeatLbl.setText("");
            TtlCtxt.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_AvlFlightsActionPerformed

    private void ClassCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassCmbActionPerformed
        // TODO add your handling code here:
        try {
           



            String Ticketcmd = "select coalesce(sum(tickets),0) as tsold from booking where flightno = " + BookingVar.flightno + " and  class = '" + ClassCmb.getSelectedItem().toString() + "' and date_format(date_flight,'%d/%m/%Y')='" + datetxt.getText() + "';";


            ResultSet rs1 = connect().executeQuery(Ticketcmd);
            rs1.next();


            String cancTick = "select sum(tickets) from booking where canceled = 'Y' and flightno = " + BookingVar.flightno + ";";


            ResultSet rs2 = connect().executeQuery(cancTick);
            rs2.next();

            int Ticketsold = rs1.getInt("tsold");
            int TicketCancel = rs2.getInt("sum(tickets)");


            if (ClassCmb.getSelectedItem().equals("Economy")) {
                BookingVar.SeatsAvl = BookingVar.ecoSeats - Ticketsold + TicketCancel;
                BookingVar.Rate = BookingVar.ecoRate;
            } else if (ClassCmb.getSelectedItem().equals("Bussiness")) {
                BookingVar.Rate = BookingVar.bussRate;
                BookingVar.SeatsAvl = BookingVar.bussSeats - Ticketsold + TicketCancel;
            } else if (ClassCmb.getSelectedItem().equals("First Class")) {
                BookingVar.Rate = BookingVar.firstRate;
                BookingVar.SeatsAvl = BookingVar.firstSeats - Ticketsold + TicketCancel;
            }
            SeatLbl.setText(BookingVar.SeatsAvl + "");


        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_ClassCmbActionPerformed

    private void No_seatsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_No_seatsKeyReleased
        // TODO add your handling code here:
        try {
            BookingVar.NuSeats = Integer.parseInt(No_seats.getText());
            TtlCtxt.setText(BookingVar.NuSeats + "x" + BookingVar.Rate + "=" + BookingVar.NuSeats * BookingVar.Rate);
            BookingVar.TtlC = BookingVar.NuSeats * BookingVar.Rate;
        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_No_seatsKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new MainForm().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void FindBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindBTNActionPerformed
        // TODO add your handling code here:
        if (!isDateValid(datetxt.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Date", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultComboBoxModel dmodel = (DefaultComboBoxModel) AvlFlights.getModel();
            dmodel.removeAllElements();
            SimpleDateFormat Dform = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Date curD = Dform.parse(datetxt.getText());
                Calendar cal = Calendar.getInstance();
                cal.setTime(curD);
                int day = cal.get(Calendar.DAY_OF_WEEK);// gets day of week             
// Connection

                String CmdSql = "select flightno,from_f,to_f from flights where flight_day like '%" + day + "%' ;";

                ResultSet rs = connect().executeQuery(CmdSql);
// Sets the model of combobox
                while (rs.next()) {
                    dmodel.addElement(rs.getString("flightno") + "," + rs.getString("from_f") + "-" + rs.getString("to_f"));

                }
                AvlFlights.setModel(dmodel);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_FindBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Booking().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALbl;
    private javax.swing.JLabel AirLbl;
    private javax.swing.JComboBox AvlFlights;
    private javax.swing.JButton BookBTN;
    private javax.swing.JButton CancelBTN;
    private javax.swing.JComboBox ClassCmb;
    private javax.swing.JLabel DLbl;
    private javax.swing.JButton FindBTN;
    private javax.swing.JLabel FromLbl;
    private javax.swing.JTextField No_seats;
    private javax.swing.JLabel SeatLbl;
    private javax.swing.JLabel ToLbl;
    private javax.swing.JLabel TtlCtxt;
    private javax.swing.JLabel busRateLbl;
    private javax.swing.JFormattedTextField datetxt;
    private javax.swing.JLabel ecoRateLbl;
    private javax.swing.JLabel firstRateLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
