package FlightPackage;

import java.sql.*;

import javax.swing.*;
/*
 * ----Flight Booking System--------- Developed by - Harsh Joshi Bhavya Giri
 * Goswami
 */

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 *
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.getRootPane().setDefaultButton(LoginBtn);
        ImageIcon icon = new ImageIcon(getClass().getResource("AWT-Plane.png"));
        setIconImage(icon.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        SigninBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Booking System");
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(470, 651));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(4, 20, 42));

        jLayeredPane1.setBackground(new java.awt.Color(9, 43, 88));

        jLabel1.setBackground(new java.awt.Color(13, 86, 148));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/boeingplane5.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 470, 650);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name -");
        jLabel2.setBounds(70, 400, 112, 22);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password -");
        jLabel3.setBounds(70, 450, 120, 22);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.PALETTE_LAYER);

        username.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        username.setBounds(210, 400, 213, 34);
        jLayeredPane1.add(username, javax.swing.JLayeredPane.PALETTE_LAYER);

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.setBounds(210, 450, 213, 34);
        jLayeredPane1.add(password, javax.swing.JLayeredPane.PALETTE_LAYER);

        LoginBtn.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        LoginBtn.setBounds(240, 510, 115, 33);
        jLayeredPane1.add(LoginBtn, javax.swing.JLayeredPane.PALETTE_LAYER);

        SigninBtn.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        SigninBtn.setText("Sign In");
        SigninBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninBtnActionPerformed(evt);
            }
        });
        SigninBtn.setBounds(240, 560, 111, 40);
        jLayeredPane1.add(SigninBtn, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Don't have an account ?   -->");
        jLabel4.setBounds(20, 560, 202, 41);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(410, 610, 45, 27);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DRAG_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(219, 237, 235));
        jLabel5.setText("Flight Booking System");
        jLabel5.setBounds(10, 40, 450, 40);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DRAG_LAYER);

        jLabel6.setBackground(new java.awt.Color(10, 37, 99));
        jLabel6.setBounds(0, 600, 470, 50);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel7.setBackground(new java.awt.Color(15, 71, 134));
        jLabel7.setOpaque(true);
        jLabel7.setBounds(0, 0, 470, 50);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 150, 190), 2));
        jSeparator1.setBounds(-10, 80, 490, 10);
        jLayeredPane1.add(jSeparator1, javax.swing.JLayeredPane.MODAL_LAYER);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/iconlogo.png"))); // NOI18N
        jLabel8.setBounds(240, 30, 180, 60);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.POPUP_LAYER);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 150, 190), 2));
        jSeparator2.setBounds(-10, 30, 500, 10);
        jLayeredPane1.add(jSeparator2, javax.swing.JLayeredPane.POPUP_LAYER);

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setBounds(10, 100, 210, 0);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int tries = 0;

    Statement connect() throws ClassNotFoundException, SQLException {//Connection Method

        Class.forName("com.mysql.jdbc.Driver");
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight_book", "root", "ipqwe320");
        Statement stmt = con.createStatement();
        return stmt;
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0); // To close the application
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        String inputUser = username.getText(); // gets username as input
        String inputPass = new String(password.getPassword()); // gets password as input



        try {


            String CmdSql = "select * from users where user_name = '" + inputUser + "' and password = '" + inputPass + "'";
// Executing the query and extracting the resultset            

            ResultSet rs = connect().executeQuery(CmdSql);

// checking the validity of the input username            

            if (!rs.next() && tries < 3) {
                tries += 1;
                if (tries == 3) {
                    JOptionPane.showMessageDialog(this, "You have entered invalid username or password.\nPlease restart the application and try again.", "Invalid entry, tries = " + tries, JOptionPane.INFORMATION_MESSAGE);
                    username.setEnabled(false);
                    password.setEnabled(false);
                    LoginBtn.setEnabled(false);
                    SigninBtn.setEnabled(false);

                } else {
                    JOptionPane.showMessageDialog(this, "Enter a valid Username or Password", "Invalid entry, try = " + tries,
                            JOptionPane.WARNING_MESSAGE);
                    username.setText("");
                    password.setText("");
                }
                return;
            }
// Setting the values to the global variables            
            UserGlobal.userID = rs.getInt("idno");
            UserGlobal.userName = rs.getString("user_name");
            UserGlobal.userPass = rs.getString("password");
            UserGlobal.userAddr = rs.getString("address");
            UserGlobal.userPhone = rs.getString("phone_no");
            UserGlobal.userCity = rs.getString("city");
            if (rs.getString("dev").equals("Y")) {
                UserGlobal.dev = true;//is developer or administrator else if dev = false ,then normal login i.e. without master record acess. 
            } else if (rs.getString("dev").equals("N")) {
                UserGlobal.dev = false;
            }

// Disposing this form              
            this.dispose();
// Opening the Main form             
            new MainForm().setVisible(true);


        } catch (Exception e) {
            // Catches the exception and displays the exception in an JOptionPane
            JOptionPane.showMessageDialog(this, e.getMessage());
        }



    }//GEN-LAST:event_LoginBtnActionPerformed

    private void SigninBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninBtnActionPerformed
        // TODO add your handling code here:
        new NewUser().setVisible(true);// Opening New User form
        this.dispose(); // Closing login form
    }//GEN-LAST:event_SigninBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton SigninBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
